### ISSUE TITLE
GSPS DICOM file examples?

### ISSUE THREAD

**Issue by FezVrasta** [mrceresa/dcmtk-offis#1]
Hi, would you be so kind to provide a set of DICOM files to test the dcmp2pgm utility? I can't find anything online.

Thanks.

**Comment by mrceresa** [comment]
Hi Federico, 
I'm not the actual developer of dcmtk, I created the package for Fedora linux in the past but I don't maintain it anymore.

Maybe you can find something useful here:
https://www.dicomlibrary.com/

Best
